vcf_files = {
    -- Blaine County Sheriff Biler
    "police2.xml",
    "police3.xml",
    "pranger.xml",
    "sheriff2.xml",
    -- Los Santos Police Department Biler
    "police71.xml",
    "police61.xml",
    "police41.xml",
    "police23.xml",
    "police21.xml",
    "police12.xml",
    "police8.xml",
    "police7.xml",
    "police6.xml",
    "police5.xml",
    "police4.xml",
    "police1.xml",
    "police.xml",
    "fbi2.xml",
    "fbi.xml",
    -- Civil Politi Biler
    "lcumkalamo.xml",
    "lcumkalamo2.xml",
    "lcumkbuffac.xml",
    "lcumkbuffs.xml",
    "lcumkradi.xml",
    "lcumkroamer.xml",
    "lcumkrumpo.xml",
    "lcumkscout.xml",
    "lcumkscout2.xml",
    "lcumksemin.xml",
    "lcumkspeedo.xml",
    "lcumkstan.xml",
    "lcumksteed.xml",
    "lcumktore.xml",
    "lcumktore2.xml",
    -- Ambulancer
    "fdnyambulance.xml",
    "ambulance.xml",
}